### ISSUE TITLE
Example for ESP32 Arduino

### ISSUE THREAD

**Issue by sdrshnptl** [Fishwaldo/esp_ghota#5]
How to make it work with ESP32 Arduino core?

**Comment by netmindz** [comment]
Is it possible?

**Comment by zekageri** [comment]
I would also be interested.

**Comment by cwoodward** [comment]
Also interested in ESP32 Arduino support

**Comment by netmindz** [comment]
You might want to try this project that was inspired by this one, but for Arduino https://github.com/axcap/Esp-GitHub-OTA

**Comment by cwoodward** [comment]
Thanks! I'll check it out.
